
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: 'password'
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: debug

ticket:
  adultPrice: 25.0
  studentPrice: 18.0
  childPrice: 12.5

reservation:
  expireLimitBookingMinutes: 15
  expireLimitAppearInPersonMinutes: 5





